In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
df=pd.read_csv("data.csv")
print(df.shape)
df.head()

(6819, 96)

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,1,0.370594,0.424389,0.405750,0.601457,0.601457,0.998969,0.796887,0.808809,0.302646,...,0.716845,0.009219,0.622879,0.601453,0.827890,0.290202,0.026601,0.564050,1,0.016469
1,1,0.464291,0.538214,0.516730,0.610235,0.610235,0.998946,0.797380,0.809301,0.303556,...,0.795297,0.008323,0.623652,0.610237,0.839969,0.283846,0.264577,0.570175,1,0.020794
2,1,0.426071,0.499019,0.472295,0.601450,0.601364,0.998857,0.796403,0.808388,0.302035,...,0.774670,0.040003,0.623841,0.601449,0.836774,0.290189,0.026555,0.563706,1,0.016474
3,1,0.399844,0.451265,0.457733,0.583541,0.583541,0.998700,0.796967,0.808966,0.303350,...,0.739555,0.003252,0.622929,0.583538,0.834697,0.281721,0.026697,0.564663,1,0.023982
4,1,0.465022,0.538432,0.522298,0.598783,0.598783,0.998973,0.797366,0.809304,0.303475,...,0.795016,0.003878,0.623521,0.598782,0.839973,0.278514,0.024752,0.575617,1,0.035490

In [3]:
from sklearn.model_selection import train_test_split

In [5]:
bankrupt= df.drop(" Net Income Flag", axis=1) 
X=bankrupt.drop("Bankrupt?", axis=1).values
y=bankrupt["Bankrupt?"].values

In [11]:
X_Train, X_test, Y_Train, y_test = train_test_split(X,y,test_size=0.10,random_state=101)

In [12]:
X_train, X_valid, y_train, y_valid= train_test_split(X_Train, Y_Train,test_size=0.25,random_state=101)

In [13]:
X_train.shape, X_valid.shape, X_test.shape, y_train.shape, y_valid.shape,  y_test.shape

((4602, 94), (1535, 94), (682, 94), (4602,), (1535,), (682,))

In [14]:
import pickle

# Assuming you already have X_train, X_valid, X_test, y_train, y_valid, y_test defined

# Dumping the data to pickle files
with open('X_train.pkl', 'wb') as file:
    pickle.dump(X_train, file)

with open('X_valid.pkl', 'wb') as file:
    pickle.dump(X_valid, file)

with open('X_test.pkl', 'wb') as file:
    pickle.dump(X_test, file)

with open('y_train.pkl', 'wb') as file:
    pickle.dump(y_train, file)

with open('y_valid.pkl', 'wb') as file:
    pickle.dump(y_valid, file)

with open('y_test.pkl', 'wb') as file:
    pickle.dump(y_test, file)

# Loading the data from pickle files
with open('X_train.pkl', 'rb') as file:
    loaded_X_train = pickle.load(file)

with open('X_valid.pkl', 'rb') as file:
    loaded_X_valid = pickle.load(file)

with open('X_test.pkl', 'rb') as file:
    loaded_X_test = pickle.load(file)

with open('y_train.pkl', 'rb') as file:
    loaded_y_train = pickle.load(file)

with open('y_valid.pkl', 'rb') as file:
    loaded_y_valid = pickle.load(file)

with open('y_test.pkl', 'rb') as file:
    loaded_y_test = pickle.load(file)

# Checking the shapes to ensure data consistency
print(loaded_X_train.shape, loaded_X_valid.shape, loaded_X_test.shape, loaded_y_train.shape, loaded_y_valid.shape, loaded_y_test.shape)

(4602, 94) (1535, 94) (682, 94) (4602,) (1535,) (682,)

In [16]:
import pandas as pd

# Assuming you already have X_train, X_valid, X_test, y_train, y_valid, y_test defined as NumPy arrays

# Convert NumPy arrays to Pandas DataFrames
X_train_df = pd.DataFrame(X_train, columns=[f'feature_{i}' for i in range(X_train.shape[1])])
X_valid_df = pd.DataFrame(X_valid, columns=[f'feature_{i}' for i in range(X_valid.shape[1])])
X_test_df = pd.DataFrame(X_test, columns=[f'feature_{i}' for i in range(X_test.shape[1])])

y_train_df = pd.DataFrame(y_train, columns=['target'])
y_valid_df = pd.DataFrame(y_valid, columns=['target'])
y_test_df = pd.DataFrame(y_test, columns=['target'])

# Concatenating features and labels for training data
training_data = pd.concat([X_train_df, y_train_df], axis=1)

# Concatenating features and labels for test data
test_data = pd.concat([X_test_df, y_test_df], axis=1)

# Saving dataframes to CSV files
training_data.to_csv('train.csv', index=False)
test_data.to_csv('test.csv', index=False)

In [17]:
training_data.head()

,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_85,feature_86,feature_87,feature_88,feature_89,feature_90,feature_91,feature_92,feature_93,target
0,0.458490,0.520497,0.509342,0.597998,0.597847,0.998920,0.797318,0.809258,0.303503,0.781513,...,0.786000,0.001269,0.623674,0.597993,0.839149,0.280973,0.026359,0.561668,0.025617,0
1,0.412129,0.416267,0.442904,0.613211,0.613211,0.998728,0.796906,0.808857,0.303184,0.781070,...,0.718107,0.000448,0.623800,0.613210,0.832859,0.281361,0.026761,0.565008,0.024724,0
2,0.480330,0.548081,0.535200,0.603886,0.603864,0.998965,0.797434,0.809360,0.303611,0.781622,...,0.805861,0.001573,0.623810,0.603881,0.840687,0.277470,0.026791,0.565158,0.044950,0
3,0.585629,0.582915,0.636704,0.618624,0.618624,0.999297,0.797754,0.809583,0.303476,0.781892,...,0.824666,0.006710,0.623487,0.618623,0.841905,0.277425,0.026857,0.565455,0.045516,0
4,0.644859,0.668229,0.667434,0.634738,0.634738,0.999429,0.797962,0.809726,0.303561,0.782016,...,0.866553,0.000431,0.624210,0.634739,0.844162,0.276480,0.026791,0.565158,0.064058,0